name: Convert stamparm/ipsum list of bad IPs(level3) to RouterOS addressList

on:
  schedule:
  - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - uses: browser-actions/setup-chrome@v1
      with:
        install-chromedriver: true
    - run: ${{ steps.setup-chrome.outputs.chrome-path }} --version
      
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies
        
    - name: Install requests
      run: pip install -r requirements.txt

    - name: Run python ipsum.py
      run: python ./ipsum-Level3-convert_to_routeros.py
    - name: Run python selenium_test.py
      run: python ./selenium_test.py

    - name: Generate tag name
      run: echo "TAG_NAME=$(date +%F-%H-%M)" >> $GITHUB_ENV

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@master
      with:
        files: ./rsc/*.rsc
        name: Automatic list generation
        tag_name: ${{ env.TAG_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 2
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    - name: Upload log files
#      uses: actions/upload-artifact@master
#      with:
#        name: Logs
#        path: logs/*.log
#      if: ${{ always() }}
