name: Run Exchange Rate Script

on:
  schedule:
    - cron: '0 11,15 * * 1-5'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Taipei
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run exchange rate script
      env:
        ALPHA_VANTAGE_API: ${{ secrets.ALPHA_VANTAGE_API }}
      run: |
        python 匯率趨勢監控.py
        
    - name: Notify on Telegram if RATE_BELOW_MA60 is set
      if: env.RATE_BELOW_MA60 != ''
      uses: appleboy/telegram-action@master
      with:
        token: '${{ secrets.TELEGRAM_BOT_TOKEN }}'
        to: '${{ secrets.TELEGRAM_CHAT_ID }}'
        message: |
          Rate Alert:
          ${{ env.RATE_BELOW_MA60 }}

