name: Run Exchange Rate Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests alpha_vantage

    - name: Run exchange rate script
      env:
        ALPHA_VANTAGE_API: ${{ secrets.ALPHA_VANTAGE_API }}
      run: |
        python 匯率趨勢監控.py
